"""Report generation for InfraProbe monitoring results.

Generates HTML, JSON, or Markdown reports from a one-time scan
of all configured targets and system metrics.
"""

import json
import logging
import time
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from jinja2 import Template

logger = logging.getLogger("infraprobe.output.report")

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>InfraProbe Report — {{ timestamp }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 1200px; margin: 0 auto; padding: 20px; background: #f5f5f5; }
        h1 { color: #2d3748; border-bottom: 2px solid #4a90d9; padding-bottom: 10px; }
        h2 { color: #4a5568; margin-top: 30px; }
        .summary { display: flex; gap: 20px; margin: 20px 0; }
        .card { background: white; border-radius: 8px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                flex: 1; text-align: center; }
        .card .value { font-size: 2em; font-weight: bold; }
        .card .label { color: #718096; font-size: 0.9em; }
        .healthy { color: #48bb78; }
        .warning { color: #ed8936; }
        .critical { color: #f56565; }
        table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px;
                overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin: 10px 0; }
        th { background: #4a90d9; color: white; padding: 12px; text-align: left; }
        td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
        tr:hover { background: #f7fafc; }
        .status-ok { color: #48bb78; font-weight: bold; }
        .status-fail { color: #f56565; font-weight: bold; }
        footer { margin-top: 40px; color: #a0aec0; text-align: center; font-size: 0.8em; }
    </style>
</head>
<body>
    <h1>InfraProbe Monitoring Report</h1>
    <p>Generated: {{ timestamp }}</p>

    <div class="summary">
        <div class="card">
            <div class="value">{{ targets_total }}</div>
            <div class="label">Targets Checked</div>
        </div>
        <div class="card">
            <div class="value healthy">{{ targets_healthy }}</div>
            <div class="label">Healthy</div>
        </div>
        <div class="card">
            <div class="value critical">{{ targets_unhealthy }}</div>
            <div class="label">Unhealthy</div>
        </div>
    </div>

    {% if ping_results %}
    <h2>Ping Results</h2>
    <table>
        <tr><th>Target</th><th>Status</th><th>RTT (avg)</th><th>Packet Loss</th></tr>
        {% for r in ping_results %}
        <tr>
            <td>{{ r.target }}</td>
            <td class="{{ 'status-ok' if r.success else 'status-fail' }}">
                {{ 'OK' if r.success else 'FAIL' }}
            </td>
            <td>{{ r.avg_rtt }}ms</td>
            <td>{{ r.packet_loss }}%</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if http_results %}
    <h2>HTTP Health Checks</h2>
    <table>
        <tr><th>URL</th><th>Status</th><th>Code</th><th>Response Time</th><th>TLS Expiry</th></tr>
        {% for r in http_results %}
        <tr>
            <td>{{ r.url }}</td>
            <td class="{{ 'status-ok' if r.success else 'status-fail' }}">
                {{ 'OK' if r.success else 'FAIL' }}
            </td>
            <td>{{ r.status_code }}</td>
            <td>{{ r.response_time }}ms</td>
            <td>{{ r.tls_expiry_days }} days</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    <footer>Generated by InfraProbe v1.0.0</footer>
</body>
</html>
"""


def generate_report(
    config: Any,
    output_format: str = "html",
    output_file: Optional[str] = None,
) -> str:
    """Generate a monitoring report from a one-time scan.

    Runs all configured checks once and compiles results into
    a report in the requested format.

    Args:
        config: InfraProbeConfig instance.
        output_format: Report format ("html", "json", "md").
        output_file: Output file path. Auto-generated if None.

    Returns:
        Path to the generated report file.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    report_data: dict[str, Any] = {
        "timestamp": timestamp,
        "targets_total": len(config.targets),
        "targets_healthy": 0,
        "targets_unhealthy": 0,
        "ping_results": [],
        "http_results": [],
    }

    # Run checks for each target
    for target in config.targets:
        for check in target.get_typed_checks():
            try:
                if check.type == "ping":
                    from infraprobe.network.icmp import ping
                    stats = ping(target=target.host, count=check.count, timeout=check.timeout)
                    success = stats.packet_loss_percent < 100
                    report_data["ping_results"].append({
                        "target": f"{target.name} ({target.host})",
                        "success": success,
                        "avg_rtt": f"{stats.avg_rtt_ms:.1f}" if stats.avg_rtt_ms else "N/A",
                        "packet_loss": stats.packet_loss_percent,
                    })
                    if success:
                        report_data["targets_healthy"] += 1
                    else:
                        report_data["targets_unhealthy"] += 1

                elif check.type == "http":
                    from infraprobe.network.http_checker import check_http
                    result = check_http(
                        url=check.url,
                        expected_status=check.expected_status,
                        check_tls=check.check_tls,
                    )
                    report_data["http_results"].append({
                        "url": check.url,
                        "success": result.success,
                        "status_code": result.status_code,
                        "response_time": f"{result.response_time_ms:.1f}",
                        "tls_expiry_days": (
                            result.tls_info.days_until_expiry if result.tls_info else "N/A"
                        ),
                    })
                    if result.success:
                        report_data["targets_healthy"] += 1
                    else:
                        report_data["targets_unhealthy"] += 1

            except Exception as e:
                logger.error("Check failed for %s: %s", target.name, e)
                report_data["targets_unhealthy"] += 1

    # Generate output
    if output_file is None:
        ext = {"html": "html", "json": "json", "md": "md"}.get(output_format, "html")
        output_file = f"infraprobe-report-{int(time.time())}.{ext}"

    if output_format == "json":
        content = json.dumps(report_data, indent=2, default=str)
    elif output_format == "md":
        content = _render_markdown(report_data)
    else:
        template = Template(HTML_TEMPLATE)
        content = template.render(**report_data)

    Path(output_file).write_text(content)
    logger.info("Report generated: %s", output_file)
    return output_file


def _render_markdown(data: dict[str, Any]) -> str:
    """Render report data as Markdown."""
    lines = [
        "# InfraProbe Monitoring Report",
        f"\nGenerated: {data['timestamp']}",
        f"\n## Summary",
        f"- Targets checked: {data['targets_total']}",
        f"- Healthy: {data['targets_healthy']}",
        f"- Unhealthy: {data['targets_unhealthy']}",
    ]

    if data["ping_results"]:
        lines.append("\n## Ping Results\n")
        lines.append("| Target | Status | RTT (avg) | Packet Loss |")
        lines.append("|--------|--------|-----------|-------------|")
        for r in data["ping_results"]:
            status = "OK" if r["success"] else "FAIL"
            lines.append(f"| {r['target']} | {status} | {r['avg_rtt']}ms | {r['packet_loss']}% |")

    if data["http_results"]:
        lines.append("\n## HTTP Health Checks\n")
        lines.append("| URL | Status | Code | Response Time | TLS Expiry |")
        lines.append("|-----|--------|------|---------------|------------|")
        for r in data["http_results"]:
            status = "OK" if r["success"] else "FAIL"
            lines.append(
                f"| {r['url']} | {status} | {r['status_code']} | "
                f"{r['response_time']}ms | {r['tls_expiry_days']} days |"
            )

    lines.append(f"\n---\n*Generated by InfraProbe v1.0.0*")
    return "\n".join(lines)
